// packages/grapys-react/src/views/GUI.tsx
import { FC, useEffect, useMemo, useRef } from "react";

import Node from "./Node";
import Edge from "./Edge";
import Loop from "./Loop";

import AddNode from "./AddNode";
import ContextEdgeMenu from "./ContextEdgeMenu";
import ContextNodeMenu from "./ContextNodeMenu";

import GraphRunner from "./GraphRunner";
import TemplateGraph from "./TemplateGraph";
import JsonViewer from "./JsonViewer";

// import { EdgeData, NodePosition, UpdateStaticValue } from "../utils/gui/type";

import { graphChat } from "../graph/chat_tinyswallow";

import { useNewEdge } from "../composable/gui";
import { graphToGUIData, handleDownload } from "../utils/gui/utils";
import { guiEdgeData2edgeData } from "../utils/utils/gui";
import { GraphData, sleep } from "graphai";
import { useLocalStore, node2Record, toGraph } from "../store/index";

const GUI: FC = () => {
  const nodes = useLocalStore((state) => state.nodes());
  const edges = useLocalStore((state) => state.edges());
  const currentData = useLocalStore((state) => state.currentData);
  const nodeRecords = useMemo(() => node2Record(nodes), [nodes]);
  const edgeDataList = useMemo(() => guiEdgeData2edgeData(edges, nodeRecords), [edges, nodeRecords]);

  const undo = useLocalStore((state) => state.undo);
  const redo = useLocalStore((state) => state.redo);
  const undoable = useLocalStore((state) => state.undoable());
  const redoable = useLocalStore((state) => state.redoable());

  const loadData = useLocalStore((state) => state.loadData);

  const contextNodeMenuRef = useRef<{ openMenu: (event: MouseEvent, rect: DOMRect, nodeIndex: number) => void; closeMenu: () => void } | null>(null);
  const contextEdgeMenuRef = useRef<{ openMenu: (event: MouseEvent, rect: DOMRect, edgeIndex: number) => void; closeMenu: () => void } | null>(null);

  const resetGraph = useLocalStore((state) => state.reset);
  const newGraphData = toGraph(currentData);

  const initData = useLocalStore((state) => state.initData);
  const updateNodePosition = useLocalStore((state) => state.updateNodePosition);
  const onSavePosition = useLocalStore((state) => state.saveNodePositionData);

  const updateGraph = (graph: GraphData) => {
    const { rawEdge, rawNode, loop } = graphToGUIData(graph);
    initData(rawNode, rawEdge, loop);
  };
  useEffect(() => {
    (async () => {
      updateGraph(graphChat);
      await sleep(1);
      onSavePosition();
    })();
  }, []);

  const { svgRef, newEdgeData, onNewEdgeStart, onNewEdge, onNewEdgeEnd, nearestData, edgeConnectable } = useNewEdge();

  const openEdgeMenu = (event: React.MouseEvent, edgeIndex: number) => {
    if (svgRef.current) {
      const rect = svgRef.current.getBoundingClientRect();
      contextEdgeMenuRef.current?.openMenu(event.nativeEvent, rect, edgeIndex);
    }
  };

  const closeMenu = () => {
    contextNodeMenuRef.current?.closeMenu();
    contextEdgeMenuRef.current?.closeMenu();
  };

  const openNodeMenu = (event: React.MouseEvent, nodeIndex: number) => {
    if (svgRef.current) {
      const rect = svgRef.current.getBoundingClientRect();
      contextNodeMenuRef.current?.openMenu(event.nativeEvent, rect, nodeIndex);
    }
  };

  const save = () => {
    const dataStr = JSON.stringify(newGraphData);
    window.localStorage.setItem("GRAPHAIGUI", dataStr);
  };

  const load = () => {
    const data = window.localStorage.getItem("GRAPHAIGUI");
    try {
      if (data) {
        const graphData = JSON.parse(data);
        loadData(graphData.metadata.data);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const setGraph = async (graph: GraphData) => {
    resetGraph();
    await sleep(1);
    updateGraph(graph);
    await sleep(1);
    onSavePosition();
  };

  return (
    <div>
      <div className="flex h-screen w-full">
        <aside className="w-48 p-4 text-center">
          <h2 className="text-lg font-bold">Menu</h2>
          <AddNode />
          <hr />
          <button
            onClick={undo}
            className={`m-1 cursor-pointer items-center rounded-full px-4 py-2 font-bold text-white ${undoable ? "bg-sky-500 hover:bg-sky-700" : "bg-sky-200"}`}
          >
            Undo
          </button>
          <button
            onClick={redo}
            className={`m-1 cursor-pointer items-center rounded-full px-4 py-2 font-bold text-white ${redoable ? "bg-sky-500 hover:bg-sky-700" : "bg-sky-200"}`}
          >
            Redo
          </button>
          <hr />
          <div>
            <button onClick={resetGraph} className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">
              Clear Graph
            </button>
          </div>
          <hr />
          <div>
            <button onClick={save} className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">
              Save Graph
            </button>
          </div>
          <div>
            <button onClick={load} className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">
              Load Graph
            </button>
          </div>
          <div>
            <button
              onClick={() => handleDownload(newGraphData)}
              className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white"
            >
              Download
            </button>
          </div>
          <hr />
          <TemplateGraph onSetGraph={setGraph} />
        </aside>
        <main className="relative flex-1">
          <div className="relative h-[100vh] overflow-hidden rounded-md border-4 border-gray-200" onClick={closeMenu}>
            <svg x="0" y="0" className="absolute h-[100%] w-full" ref={svgRef}>
              {edgeDataList.map((edge, index) => (
                <Edge
                  key={`edge-${edge.source}-${edge.target}-${index}`}
                  sourceData={edge.source}
                  targetData={edge.target}
                  index={index}
                  openEdgeMenu={openEdgeMenu}
                />
              ))}
              {newEdgeData && <Edge sourceData={newEdgeData.source} targetData={newEdgeData.target} isConnectable={edgeConnectable} />}{" "}
            </svg>
            <Loop />
            {nodes.map((node, index) => (
              <Node
                key={`${node.nodeId}-${index}`}
                nodeIndex={index}
                nodeData={node}
                nearestData={nearestData}
                onUpdatePosition={(pos) => updateNodePosition(index, pos)}
                onSavePosition={onSavePosition}
                onNewEdgeStart={onNewEdgeStart}
                onNewEdge={onNewEdge}
                onNewEdgeEnd={onNewEdgeEnd}
                onOpenNodeMenu={(e) => openNodeMenu(e, index)}
              />
            ))}
            <ContextNodeMenu ref={contextNodeMenuRef} />
            <ContextEdgeMenu ref={contextEdgeMenuRef} />
            <div className="justify-top pointer-events-none absolute top-0 right-0 z-10 flex flex-row items-start space-x-4 pt-4 pr-4 pb-4">
              <JsonViewer jsonData={newGraphData} />
              <GraphRunner graphData={newGraphData} />
            </div>
          </div>
        </main>
      </div>
      <div className="bg-red-200 bg-red-300 bg-red-400 bg-red-500"></div>
      <div className="bg-green-200 bg-green-300 bg-green-400 bg-green-500"></div>
      <div className="bg-blue-200 bg-blue-300 bg-blue-400 bg-blue-500"></div>
      <div className="bg-yellow-200 bg-yellow-300 bg-yellow-400 bg-yellow-500"></div>
      <div className="bg-violet-200 bg-violet-500"></div>
    </div>
  );
};

export default GUI;

// packages/grapys-vue/src/views/GUI.vue
<script lang="ts">
import { defineComponent, computed, onMounted, ref } from "vue";
import Node2 from "./Node2.vue";
import NodeEditorPanel from "./NodeEditorPanel.vue";
import Edge from "./Edge.vue";
import Loop from "./Loop.vue";

import ContextEdgeMenu from "./ContextEdgeMenu.vue";
import ContextNodeMenu from "./ContextNodeMenu.vue";

import GraphRunner from "./GraphRunner.vue";
import JsonViewer from "./JsonViewer.vue";

import SideMenu from "./SideMenu.vue";

import { EdgeData, NodePosition, UpdateStaticValue } from "../utils/gui/type";

import { graphChat } from "../graph/chat_tinyswallow";

import { useNewEdge } from "../composable/gui";
import { usePanAndScroll } from "../composable/usePanAndScroll";
import { guiEdgeData2edgeData } from "../utils/gui/utils";
import { useStore } from "../store";

export default defineComponent({
  components: {
    SideMenu,
    Node2,
    Edge,
    Loop,
    ContextEdgeMenu,
    ContextNodeMenu,
    NodeEditorPanel,
    GraphRunner,
    JsonViewer,
  },
  setup() {
    const store = useStore();
    const contextEdgeMenu = ref();
    const contextNodeMenu = ref();
    const selectedNodeIndex = ref<number | null>(null);
    const isNodeEditorOpen = computed(() => selectedNodeIndex.value !== null);
    const panelKey = ref(0);
    const mainContainer = ref();
    store.initFromGraphData(graphChat);

    // ノードドラッグ状態の管理
    const isNodeDragging = ref(false);

    const handleNodeDragStart = () => {
      isNodeDragging.value = true;
    };

    const handleNodeDragEnd = () => {
      isNodeDragging.value = false;
    };

    onMounted(() => {
      saveNodePosition();
      setupPanAndScroll();
    });

    const updateNodePosition = (index: number, pos: NodePosition) => {
      store.updateNodePosition(index, pos);
    };
    const saveNodePosition = () => {
      store.saveNodePositionData();
    };
    const updateStaticNodeValue = (index: number, value: UpdateStaticValue, saveHistory: boolean) => {
      store.updateStaticNodeValue(index, value, saveHistory);
    };
    const updateNestedGraph = (index: number, value: UpdateStaticValue) => {
      store.updateNestedGraph(index, value);
    };

    const edgeDataList = computed<EdgeData[]>(() => {
      return guiEdgeData2edgeData(store.edges, store.nodeRecords);
    });

    const { svgRef, newEdgeData, onNewEdgeStart, onNewEdge, onNewEdgeEnd, nearestData, edgeConnectable } = useNewEdge();

    // パン（掴んで動かす）とスクロール機能のセットアップ
    const { setupPanAndScroll } = usePanAndScroll(mainContainer, isNodeDragging, newEdgeData);

    const openEdgeMenu = (event: MouseEvent, edgeIndex: number) => {
      const rect = svgRef.value.getBoundingClientRect();
      contextEdgeMenu.value.openMenu(event, rect, edgeIndex);
    };
    const closeMenu = () => {
      contextEdgeMenu.value.closeMenu();
      contextNodeMenu.value.closeMenu();
    };
    const openNodeMenu = (event: MouseEvent, nodeIndex: number) => {
      const rect = svgRef.value.getBoundingClientRect();
      contextNodeMenu.value.openMenu(event, rect, nodeIndex);
    };
    const openNodeEditor = (_event: MouseEvent, nodeIndex: number) => {
      // remount only if different node is clicked
      if (selectedNodeIndex.value === nodeIndex) return;
      selectedNodeIndex.value = nodeIndex;
      panelKey.value += 1;
    };

    const showJsonView = ref(false);
    const showChat = ref(false);

    return {
      updateNodePosition,
      saveNodePosition,
      updateStaticNodeValue,
      updateNestedGraph,

      store,

      edgeDataList,
      onNewEdgeStart,
      onNewEdge,
      onNewEdgeEnd,
      newEdgeData,
      svgRef,
      nearestData,

      contextEdgeMenu,
      contextNodeMenu,
      openEdgeMenu,
      openNodeMenu,
      openNodeEditor,
      closeMenu,

      edgeConnectable,

      showJsonView,
      showChat,
      mainContainer,
      selectedNodeIndex,
      isNodeEditorOpen,
      panelKey,

      handleNodeDragStart,
      handleNodeDragEnd,
    };
  },
});
</script>

<template>
  <div>
    <div class="flex h-screen">
      <aside class="w-48 p-4 text-center">
        <SideMenu />
      </aside>
      <main class="flex-1">
        <div
          ref="mainContainer"
          class="relative overflow-auto rounded-md border-4 border-gray-200"
          style="width: calc(100vw - 192px); height: calc(100vh - 40px)"
          @click="closeMenu"
        >
          <div class="relative" style="width: 2000px; height: 1500px">
            <Loop />
            <svg x="0" y="0" class="pointer-events-none absolute h-full w-full" ref="svgRef">
              <Edge
                v-for="(edge, index) in edgeDataList"
                :key="['edge', edge.source, edge.target, index].join('-')"
                :source-data="edge.source"
                :target-data="edge.target"
                class="pointer-events-auto"
                @dblclick="(e: MouseEvent) => openEdgeMenu(e, index)"
              />
              <Edge
                v-if="newEdgeData"
                :source-data="newEdgeData.source"
                :target-data="newEdgeData.target"
                class="pointer-events-auto"
                :is-connectable="edgeConnectable"
              />
            </svg>
            <Node2
              v-for="(node, index) in store.nodes"
              :key="[node.nodeId, index].join('-')"
              :node-index="index"
              :node-data="node"
              :nearest-data="nearestData"
              :is-connectable="edgeConnectable"
              @update-position="(pos: NodePosition) => updateNodePosition(index, pos)"
              @update-static-node-value="updateStaticNodeValue(index, $event, true)"
              @update-nested-graph="updateNestedGraph(index, $event)"
              @save-position="saveNodePosition"
              @new-edge-start="onNewEdgeStart"
              @new-edge="onNewEdge"
              @new-edge-end="onNewEdgeEnd"
              @open-node-menu="(e: MouseEvent) => openNodeMenu(e, index)"
              @open-node-edit-menu="(e: MouseEvent) => openNodeEditor(e, index)"
              @node-drag-start="handleNodeDragStart"
              @node-drag-end="handleNodeDragEnd"
            />
            <ContextEdgeMenu ref="contextEdgeMenu" />
            <ContextNodeMenu ref="contextNodeMenu" />
          </div>
        </div>
        <div class="h-100vh pointer-events-none absolute top-0 right-0 z-10 flex max-h-screen flex-col items-end space-y-4 pt-4 pr-4 pb-4">
          <div class="flex flex-row items-start space-x-4">
            <button
              class="pointer-events-auto m-1 cursor-pointer items-center rounded-full border-1 border-gray-300 bg-gray-100 px-4 py-2 text-black"
              @click="showJsonView = !showJsonView"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M14.25 9.75 16.5 12l-2.25 2.25m-4.5 0L7.5 12l2.25-2.25M6 20.25h12A2.25 2.25 0 0 0 20.25 18V6A2.25 2.25 0 0 0 18 3.75H6A2.25 2.25 0 0 0 3.75 6v12A2.25 2.25 0 0 0 6 20.25Z"
                />
              </svg>
            </button>
            <button
              class="pointer-events-auto m-1 cursor-pointer items-center rounded-full border-1 border-gray-300 bg-gray-100 px-4 py-2 text-black"
              @click="showChat = !showChat"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z"
                />
              </svg>
            </button>
          </div>
          <div class="flex flex-row items-start space-x-4">
            <JsonViewer v-if="showJsonView" :json-data="store.graphData" :is-open="showJsonView" @close="showJsonView = false" />
            <GraphRunner :class="{ hidden: !showChat }" :graph-data="store.graphData" :is-open="showChat" @close="showChat = false" />
            <NodeEditorPanel
              :key="panelKey"
              :is-open="isNodeEditorOpen"
              v-if="isNodeEditorOpen"
              :node-index="selectedNodeIndex as number"
              @close="selectedNodeIndex = null"
              @update-static-node-value="(v: UpdateStaticValue) => updateStaticNodeValue(selectedNodeIndex as number, v, true)"
              @update-nested-graph="(v: UpdateStaticValue) => updateNestedGraph(selectedNodeIndex as number, v)"
            />
          </div>
        </div>
      </main>
    </div>
  </div>
</template>
