// packages/grapys-vue/src/plugins/graphai/components/NodeStaticValue.vue
<template>
  <label class="text-xs text-gray-300">Value</label>
  <select v-model="dataType" class="w-full resize-none rounded-md border border-gray-300 p-1 text-black" @change="dataTypeUpdate">
    <option v-for="(option, k) in staticNodeOptions" :value="option.value" :key="k">
      {{ option.name }}
    </option>
  </select>
  <div v-show="['text', 'data'].includes(dataType)">
    <textarea
      placeholder="Enter the text"
      class="w-full resize-none rounded-md border border-gray-300 p-1 text-black"
      v-model="textAreaValue"
      ref="textareaRef"
      :rows="rows"
      @mousedown.stop
      @touchstart.stop
      @wheel.stop
    ></textarea>
    <div v-if="['data'].includes(dataType)">
      {{ isValidData ? "valid" : "invalid" }}
    </div>
  </div>
  <div v-show="['number'].includes(dataType)">
    <input
      type="number"
      class="w-full resize-none rounded-md border border-gray-300 p-1 text-black"
      v-model="numberValue"
      ref="inputRef"
      @mousedown.stop
      @touchstart.stop
    />
  </div>
  <div v-show="['boolean'].includes(dataType)">
    <select v-model="booleanValue" ref="selectFormRef" @change="selectUpdate">
      <option value="true">True</option>
      <option value="false">False</option>
    </select>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, PropType, onMounted, onBeforeUnmount, watch } from "vue";
import type { GUINodeData } from "../../../utils/gui/type";
import { staticNodeOptions } from "../../../utils/gui/classUtils";

export default defineComponent({
  props: {
    nodeData: {
      type: Object as PropType<GUINodeData>,
      required: true,
    },
  },
  emits: ["focusEvent", "blurEvent", "updateStaticValue"],
  setup(props, ctx) {
    const textareaRef = ref();
    const inputRef = ref();
    const selectFormRef = ref();
    const rows = ref(3);

    const dataType = ref(props.nodeData.data.staticNodeType ?? "text");
    const numberValue = ref(props.nodeData.data.staticNodeType === "number" ? String(props.nodeData.data.value ?? "0") : "0");
    const booleanValue = ref(props.nodeData.data.staticNodeType === "boolean" ? (props.nodeData.data.value === true ? "true" : "false") : "false");
    const textAreaValue = ref(
      String(props.nodeData.data.staticNodeType === "data" ? JSON.stringify(props.nodeData.data.value, null, 2) : (props.nodeData.data.value ?? "")),
    );

    const focusEvent = (event: FocusEvent) => {
      if (event.target instanceof HTMLTextAreaElement) {
        ctx.emit("focusEvent");
        rows.value = 10;
      }
    };

    // update func
    const updateData = () => {
      const value = (() => {
        if (dataType.value === "data" && isValidData.value) {
          return JSON.parse(textAreaValue.value);
        }
        return textAreaValue.value;
      })();

      ctx.emit("updateStaticValue", {
        value,
        staticNodeType: dataType.value,
      });
    };
    const updateNumber = () => {
      const value = (() => {
        if (dataType.value === "number") {
          return Number(numberValue.value ?? "0");
        }
      })();
      ctx.emit("updateStaticValue", {
        value,
        staticNodeType: dataType.value,
      });
    };
    const updateBoolean = () => {
      ctx.emit("updateStaticValue", {
        value: booleanValue.value === "true",
        staticNodeType: dataType.value,
      });
    };
    // end of update func

    const blurTextareaEvent = (event: FocusEvent) => {
      if (event.target instanceof HTMLTextAreaElement) {
        rows.value = 3;
        ctx.emit("blurEvent");
        updateData();
      }
    };
    const blurInputEvent = () => {
      updateNumber();
    };

    const dataTypeUpdate = () => {
      if (["data", "text"].includes(dataType.value)) {
        updateData();
      }
      if (dataType.value === "boolean") {
        updateBoolean();
      }
      if (dataType.value === "number") {
        updateNumber();
      }
    };
    const selectUpdate = () => {
      if (dataType.value === "boolean") {
        updateBoolean();
      }
    };
    // for redo
    watch(
      () => props.nodeData.data.value,
      (value) => {
        if (dataType.value === "boolean") {
          booleanValue.value = value ? "true" : "false";
        } else if (["data", "text"].includes(dataType.value)) {
          if (value !== null && typeof value === "object") {
            textAreaValue.value = JSON.stringify(value, null, 2);
          } else {
            textAreaValue.value = value as string;
          }
        } else if (dataType.value === "number") {
          numberValue.value = String(value);
        } else {
          // nothing
        }
      },
    );
    watch(
      () => props.nodeData.data.staticNodeType,
      (staticNodeType) => {
        if (staticNodeType && dataType.value !== staticNodeType) {
          dataType.value = staticNodeType;
        }
      },
    );

    const isValidData = computed(() => {
      if (dataType.value === "data") {
        try {
          JSON.parse(textAreaValue.value);
        } catch (__e) {
          return false;
        }
      }
      return true;
    });

    onMounted(() => {
      textareaRef.value.addEventListener("focus", focusEvent);
      textareaRef.value.addEventListener("blur", blurTextareaEvent);
      inputRef.value.addEventListener("blur", blurInputEvent);
    });
    onBeforeUnmount(() => {
      textareaRef.value.removeEventListener("focus", focusEvent);
      textareaRef.value.removeEventListener("blur", blurTextareaEvent);
      inputRef.value.removeEventListener("blur", blurInputEvent);
    });
    return {
      inputRef,
      textareaRef,
      selectFormRef,
      dataType,
      rows,
      booleanValue,
      numberValue,
      textAreaValue,
      staticNodeOptions,
      isValidData,
      selectUpdate,
      dataTypeUpdate,
    };
  },
});
</script>

// packages/grapys-react/src/views/NodeStaticValue.tsx
import { useState, useEffect, useRef, useCallback, ChangeEventHandler } from "react";
import type { GUINodeData, UpdateStaticValue, StaticNodeType } from "../utils/gui/type";
import { staticNodeOptions } from "../utils/utils/classUtils";
import { isObject } from "graphai";

interface NodeStaticValueProps {
  nodeData: GUINodeData;
  onFocus: () => void;
  onBlur: () => void;
  onUpdateStaticValue: (value: UpdateStaticValue) => void;
}
/*
  Handle the value of a static node.
  In the form, it is a text field, and nodeData contains the corresponding data.
  If the data is in a valid JSON format, it is stored as data; otherwise, it is saved as text.
  The form value can be changed either by user input or by modifications from history.
  Be careful when making changes and thoroughly test to ensure history functions correctly.
  History is saved on blur, except for boolean values, which are saved on change.
*/

const NodeStaticValue: React.FC<NodeStaticValueProps> = ({ nodeData, onFocus, onBlur, onUpdateStaticValue }) => {
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const selectFormRef = useRef(null);

  const [dataType, setDataType] = useState(nodeData.data.staticNodeType ?? "text");
  const [numberValue, setNumberValue] = useState("0");
  const [booleanValue, setBooleanValue] = useState("true");
  const [textAreaValue, setTextAreaValue] = useState<string>(
    nodeData.data.staticNodeType === "data" ? JSON.stringify(nodeData.data.value, null, 2) : ((nodeData.data.value ?? "") as string),
  );
  const [rows, setRows] = useState(3);

  const isValidData = useCallback(() => {
    if (dataType === "data") {
      try {
        JSON.parse(textAreaValue);
        return true;
      } catch {
        return false;
      }
    }
    return true;
  }, [textAreaValue, dataType]);

  const handleFocus = (event: FocusEvent) => {
    if (event.target instanceof HTMLTextAreaElement) {
      onFocus && onFocus();
      setRows(10);
    }
  };
  const handleBlur = useCallback(
    (event: FocusEvent) => {
      if (event.target instanceof HTMLTextAreaElement) {
        setRows(3);
        onBlur && onBlur();
        const value = dataType === "data" && isValidData() ? JSON.parse(textAreaValue) : textAreaValue;
        onUpdateStaticValue && onUpdateStaticValue({ value, staticNodeType: dataType });
      }
    },
    [dataType, textAreaValue],
  );

  const handleNumberBlur = useCallback(() => {
    if (dataType === "number") {
      onUpdateStaticValue && onUpdateStaticValue({ value: Number(numberValue), staticNodeType: dataType });
    }
  }, [dataType, numberValue]);

  const handleBooleanChange: ChangeEventHandler<HTMLSelectElement> = useCallback(
    (e) => {
      setBooleanValue(e.target.value);
      onUpdateStaticValue &&
        onUpdateStaticValue({
          value: e.target.value === "true",
          staticNodeType: dataType,
        });
    },
    [dataType, booleanValue],
  );

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.addEventListener("focus", handleFocus);
      textareaRef.current.addEventListener("blur", handleBlur);
    }
    if (inputRef.current) {
      inputRef.current.addEventListener("blur", handleNumberBlur);
    }
    return () => {
      if (textareaRef.current) {
        textareaRef.current.removeEventListener("focus", handleFocus);
        textareaRef.current.removeEventListener("blur", handleBlur);
      }
      if (inputRef.current) {
        inputRef.current.removeEventListener("blur", handleNumberBlur);
      }
    };
  }, [handleBlur, handleNumberBlur]);

  useEffect(() => {
    const { staticNodeType, value } = nodeData.data;
    if (staticNodeType) {
      if (staticNodeType !== dataType) {
        setDataType(staticNodeType);
      }
      if (["text", "data"].includes(staticNodeType)) {
        const textData = isObject(value) ? JSON.stringify(value, null, 2) : (value as string);
        if (textAreaValue !== textData) {
          setTextAreaValue(textData);
        }
      }
      if (["boolean"].includes(staticNodeType)) {
        const valueText = value ? "true" : "false";
        if (valueText !== booleanValue) {
          setBooleanValue(valueText);
        }
      }
      if (["number"].includes(staticNodeType)) {
        const valueText = String(value);
        if (valueText !== numberValue) {
          setNumberValue(valueText);
        }
      }
    }
  }, [nodeData.data]);

  return (
    <div>
      <label className="text-xs text-gray-300">Value</label>
      <select
        value={dataType}
        onChange={(e) => setDataType(e.target.value as StaticNodeType)}
        className="w-full resize-none rounded-md border border-gray-300 p-1 text-black"
      >
        {staticNodeOptions.map((option, k) => (
          <option key={k} value={option.value}>
            {option.name}
          </option>
        ))}
      </select>
      {["text", "data"].includes(dataType) && (
        <div>
          <textarea
            placeholder="Enter the text"
            className="w-full resize-none rounded-md border border-gray-300 p-1 text-black"
            value={textAreaValue}
            onChange={(e) => setTextAreaValue(e.target.value)}
            ref={textareaRef}
            rows={rows}
          />
          {dataType === "data" && <div>{isValidData() ? "valid" : "invalid"}</div>}
        </div>
      )}
      {dataType === "number" && (
        <input
          type="number"
          className="w-full resize-none rounded-md border border-gray-300 p-1 text-black"
          value={numberValue}
          onChange={(e) => setNumberValue(e.target.value)}
          ref={inputRef}
        />
      )}
      {dataType === "boolean" && (
        <select value={booleanValue} onChange={handleBooleanChange} ref={selectFormRef}>
          <option value="true">True</option>
          <option value="false">False</option>
        </select>
      )}
    </div>
  );
};

export default NodeStaticValue;
